name: Update Codespaces

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Update Codespaces
              uses: github/update-codespaces@v1
              with:
                  location: .